name: Build GTTool APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK Command Line Tools
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
        rm cmdline-tools.zip
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Install Android SDK Components
      run: |
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

    - name: Install NDK
      run: |
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        yes | sdkmanager "ndk;25.1.8937393"

    - name: Install CMake
      run: |
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
        yes | sdkmanager "cmake;3.22.1"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Clean Gradle cache
      run: ./gradlew clean --no-daemon  # Clean cache to avoid stale daemon issues

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace --no-daemon --parallel=false -Dorg.gradle.jvmargs="-Xmx4g -XX:MaxMetaspaceSize=512m"  # Heap increase, parallel off, no daemon

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GTTool-Debug-APK
        path: app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
